### ISSUE TITLE
Bearer Auth Security Scheme

### ISSUE THREAD

**Issue by mplachter** [go-openapi/spec#115]
Any reason Bearer Auth Scheme is not added?
https://swagger.io/docs/specification/authentication/bearer-authentication/

**Comment by casualjim** [comment]
Because that's part of openapi 3.0. in 2.0 that is oauth access token https://swagger.io/docs/specification/2-0/authentication/

**Comment by mplachter** [comment]
Oh well than that makes sense... I will close this.

**Comment by zhasulan** [comment]
> Because that's part of openapi 3.0. in 2.0 that is oauth access token https://swagger.io/docs/specification/2-0/authentication/

Ok, When Go Open Api will be corresponded OpenApi 3.0?

**Comment by zhasulan** [comment]
> > Because that's part of openapi 3.0. in 2.0 that is oauth access token https://swagger.io/docs/specification/2-0/authentication/
> 
> Ok, When Go Open Api will be corresponded OpenApi 3.0?

ups, i'm find the new repo https://github.com/go-openapi/spec3
