### ISSUE TITLE
`AdditionalProperties` doesn't differ empty schema or explicit `false`

### ISSUE THREAD

**Issue by magodo** [go-openapi/spec#148]
Per the documentation: https://swagger.io/docs/specification/data-models/dictionaries/. The following two schemas are the same:

**case: empty schema**

```json
{
  "additionalProperties": {}
}
```

**case: true**

```json
{
  "additionalProperties": true
}
```

Also, from JSON Schema: https://json-schema.org/understanding-json-schema/reference/object.html#additional-properties:

> Setting the additionalProperties schema to false means no additional properties will be allowed.

Which means following schema is different than **case: empty schema**:

**case: false**

```json
{
  "additionalProperties": false
}
```

However, both **case: empty schema** and **case: false** are now parsed into the same value:

```shell
~/tmp/swagger via 🐹 v1.16.5 took 6s 
💤 cat a.json
{
    "definitions": {
        "empty": {
            "additionalProperties": {}
        },
        "false": {
            "additionalProperties": false
        }
    }
}


~/tmp/swagger via 🐹 v1.16.5 
💤 swagger expand a.json
{
  "paths": null,
  "definitions": {
    "empty": {
      "additionalProperties": false
    },
    "false": {
      "additionalProperties": false
    }
  }
}
```

**Comment by fredbi** [comment]
@magodo  yep this is indeed a bug. I wonder how this one could have remained hidden for so long...
Notice that the same issue occurs for "additionalItems".

I am testing a fix. Now checking that go-swagger test suite works fine with it.
