### ISSUE TITLE
Add Notice file to complete the Apache-2.0 requirements

### ISSUE THREAD

**Issue by Shnitzelil** [go-openapi/spec#155]
Hi,

Our legal department require us to point to Notice file in this repository.
Could you please add simple one.

Best Regards

**Comment by fredbi** [comment]
That's documentation for Apache Software Foundation projects. It is not mandatory for maintainers choosing to release their projects under Apache-2.0 to add a NOTICE file.

As far as what ASF project NOTICE files should contain, click on MUST: http://www.apache.org/legal/src-headers.html#notice

As per the Apache license terms (https://www.apache.org/legal/apply-license.html):
```
Understanding the 2.0 license

The ALv2 is [this set](https://www.apache.org/licenses/LICENSE-2.0.txt) of self-documented copyright and patent licensing terms. Anyone can use the license, not just the ASF and its projects, and can be [applied](https://www.apache.org/licenses/LICENSE-2.0.html#apply) by reference to the versioned license terms. An appendix to the license describes how to do this.

Note that the ASF does not use copyright assignment and that the original authors retain the copyrights for individual parts of the collective work . The method described in the appendix is only suitable for copyright owners, so the ASF uses a variation of this method.

Section 4d of the [license](https://www.apache.org/licenses/LICENSE-2.0.txt) provides for attribution notices to be included with a work in a [NOTICE](https://www.apache.org/licenses/example-NOTICE.txt) file, so the attribution notices remains, in some form, within any derivative works. Apache projects must [include correct NOTICE documents](http://www.apache.org/legal/src-headers.html#notice) in every distribution.
```

**Comment by fredbi** [comment]
I believe this extra licensing requirement is not required. @casualjim  perhaps we could close this issue?

**Comment by fredbi** [comment]
Adding a NOTICE is not a requirement. Besides, it has a viral effect and propagates to consumers.
Not about to that unless a more compelling argument is provided. Closing.
