### ISSUE TITLE
Is go-openapi handing `description` correctly in referenced definitions?

### ISSUE THREAD

**Issue by zxchris** [go-openapi/spec#22]
First, thank you for go-openapi, you've made our life so much easier!

But we think we've found something incorrect. A user of our documentation tool `DapperDox` has raised an issue with the handling of `description` members in referenced definitions, and I've tracked the behaviour down to go-openapi, but need clarification as to whether this is expected behaviour or not.

In case it matters, DapperDox does the following to load a specification:

```golang
func loadSpec(url string) (*loads.Document, error) {
    document, err := loads.Spec(url)
    if err != nil {
        return nil, err
    }

    err = spec.ExpandSpec(document.Spec(), nil)
    if err != nil {
        return nil, err
    }

    return document, nil
}
```

After which, it processes `document.Spec()` and does it's stuff.

However, consider the following simple OpenAPI specification (note the subtle difference in the reference declaration between `first` and `second`, where  `second` wraps the `$ref` in an `"items": { }` construct:

```javascript
{
  "x-navigateMethodsByName": true,
  "definitions": {
    "ItemsTest": {
      "type": "object",
      "title": "ItemsTest",
      "properties": {
        "first": {
          "type": "object",
          "description": "first property",
          "$ref": "#/definitions/MyObject"
        },
        "second": {
          "type": "object",
          "description": "second property",
          "items": {
            "$ref": "#/definitions/MyObject"
          }
        }

      }
    },
    "MyObject": {
      "type": "object",
      "title": "ThisIsTheSubDefinition",
      "properties": {
        "leaf": {
          "description": "leaf",
          "type": "string"
        }
      }
    }
  },
  "info": {
    "title": "minimal"
  },
  "swagger": "2.0",
  "paths": {
    "/items": {
      "get": {
        "summary": "go-openapi test",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/ItemsTest"
            }
          }
        }
      }
    }
  }
}
```

Having carefully looked at the OpenAPI 2.0 specification (which isn't very explicit in this case) and looked at petstore and a number of other specifications, we have concluded that the `items` member should not be used when referring to other definitions, only in the case where `type` is `array`.

Now, if we dump out document.Spec() and trace through, we find that the property `first` **does not** have a `Description` value (empty):

```golang
     Properties: (map[string]spec.Schema) (len=2) {
      (string) (len=5) "first": (spec.Schema) {
       VendorExtensible: (spec.VendorExtensible) {
        Extensions: (spec.Extensions) <nil>
       },
       SchemaProps: (spec.SchemaProps) {
        ID: (string) "",
        Ref: (spec.Ref) ,
        Schema: (spec.SchemaURL) "",
        Description: (string) "",
        Type: (spec.StringOrArray) (len=1 cap=1) {
         (string) (len=6) "object"
        },
        Format: (string) "",
        Title: (string) (len=22) "ThisIsTheSubDefinition",
```

In fact, the string "`second property`" does not appear in the dump of `document.Spec()` at all (it does if we dump out `document` itself, but the information at that level is not usable).

Conversely, property `second` *does* have a  correct`Description`, and is the expected case (taking the description from the referring property and not the referred to object):

```golang
      (string) (len=6) "second": (spec.Schema) {
       VendorExtensible: (spec.VendorExtensible) {
        Extensions: (spec.Extensions) <nil>
       },
       SchemaProps: (spec.SchemaProps) {
        ID: (string) "",
        Ref: (spec.Ref) ,
        Schema: (spec.SchemaURL) "",
        Description: (string) (len=15) "second property",
        Type: (spec.StringOrArray) (len=1 cap=1) {
         (string) (len=6) "object"
        },
```

I note, however that the structures are different - wrapping `$ref` in `"items":{}` in the second case produces a more complicated tree.

If we add a `description` member to the `MyObject` definition, then that is the description seen for `first` instead of blank. 

```javascript
"MyObject": {
      "type": "object",
      "title": "ThisIsTheSubDefinition",
      "description": "Does This Override?",
      "properties": {
        "leaf": {
          "description": "leaf",
          "type": "string"
        }
      }
    }
```

gives:

```golang
     Properties: (map[string]spec.Schema) (len=2) {
      (string) (len=5) "first": (spec.Schema) {
       VendorExtensible: (spec.VendorExtensible) {
        Extensions: (spec.Extensions) <nil>
       },
       SchemaProps: (spec.SchemaProps) {
        ID: (string) "",
        Ref: (spec.Ref) ,
        Schema: (spec.SchemaURL) "",
        Description: (string) (len=19) "Does This Override?",
```

Essentially, it appears that without the `"items":{}` wrapper, the referenced definition is directly merging into the referring property, thus overriding `Description` with an empty field (and probably other members too).

Can you confirm our analysis?

Hopefully we can find a solution soon, as the documentation DapperDox is producing for users is wrong.

Best regards!

**Comment by casualjim** [comment]
That is correct but it is also the expected behavior. JSON schema states that other properties in an object with $ref need to be ignored. http://json-schema.org/latest/json-schema-core.html#rfc.section.7

Now to solve your issue you can make use of allOf in the first item, so something like this will get you the desired outcome:

```json
{
  "first": {
    allOf : [
      {
        "type": "object",
        "description": "first property"
      },
      {
        "$ref": "#/definitions/MyObject"
      }
    ]
  }
}
```

**Comment by zxchris** [comment]
Ah, okay. I've not seen this done that way before, and not quite got my head around it!

I've given that a quick go and can see the `Description` in the dump, which is great. Understanding the problem is, for us, the first step to advising DapperDox users!

DapperDox still isn't picking up the description properly, but we can sort that.

**Comment by zxchris** [comment]
That all makes complete sense now (finally, clarity!) and thanks for the help. One last question: Is there anything in `go-openpi` that can merge down an `allOf` definition into a `spec.Schema`? We've not found anything.

Our current `allOf` processing won't handle the case you describe as is, because it expects `allOf` to be used to combine complete resource definitions, not to merge partial but valid schema objects to create a resource definition. The **correct** solution appears to be to first merge-down the `allOf` into a `spec.Schema`. It sounds like something you'd already be doing somewhere?

chris

**Comment by casualjim** [comment]
I have a flatten command and an expand command on the swagger tool. They might give you what you need.
You could potentially look at this as an example: https://github.com/go-openapi/analysis/blob/master/flatten.go

**Comment by zxchris** [comment]
Great. I'll check it out.

**Comment by casualjim** [comment]
I assume that this resolved your issue for you, if not please reopen
