### ISSUE TITLE
Question regarding to SchemaProps.ID

### ISSUE THREAD

**Issue by rmohr** [go-openapi/spec#23]
If I look at the `SchemaProps` definition, I see that the ID is marshalled into json:

```golang
type SchemaProps struct {
	ID                   string            `json:"id,omitempty"`
}
```

Is there a specific reason for that? Because when I marshal the definitions to json, this ID is also added, but according to openapi the `id` field is not part of the spec and the validation in some validators fails.

Can we change that to ``json:"-,omitempty"`` or is there another way of marshalling the spec?

/cc @emicklei @wsong

**Comment by casualjim** [comment]
I found jsonschema compatibility more important. Do you have a concrete example of a validator that fails?

**Comment by rmohr** [comment]
Sorry for the late response.

Examples are:
 * http://editor.swagger.io/#!/
 * http://bigstickcarpet.com/swagger-parser/www/index.html

You can pass in the [petshop](https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v2.0/yaml/petstore.yaml) example and add the id field there.

They do a schema validation too and since it is not part of the schema, they complain about it.
