### ISSUE TITLE
How can I maintain (or otherwise expose) the order of properties in an object?

### ISSUE THREAD

**Issue by MartinDelVecchio** [go-openapi/spec#24]
We are using YAML/Swagger to define our APIs, and react-jsonschema-form to present them in a UI.

I get an expanded/resolved version of the JSON Schema via:

   document, err := loads.spec (myYamlPath)
   if err == nil {
      expanded := document.Expanded()
   }

This works great, with one major exception:  the order of each object's properties, as defined in the original YAML file, is lost.  The problem is in the SchemaProps struct in spec/schema.go:

	Properties           map[string]*Schema `json:"properties,omitempty"`

Because this field is a map, Go's range() iterates over the keys (property names) in random order.  I understand that this is a design goal of Go, and that it cannot be hacked around in a Go map.

So I have been trying to retain the order of the properties by adding another field to SchemaProps:

	ProeprtyNames      []string           `json:"x-UiOrder,omitempty"`

Then wherever I see a value being set in the Properties field, I append its name to my list.   I do this in the schema's SetProperty() method, which I changed expandSchema() to use.  This results in pretty much what I want in the final JSON document; for example:

                  "schema" : {
                     "description" : "An error",
                     **"x-UiOrder" : [
                        "message",
                        "code",
                        "fields"
                     ],**

Unfortunately, these property names are _still_ in random order, due to the range in expandSchema():

	for k := range target.Properties {

This is a Go range over a map, and thus it is random.  I can't seem to find where **target.Properties** gets populated here.

Can somebody tell me where I should look to fix this?  Or explain to me why my goal is impossible to achieve?

Thanks.

**Comment by MartinDelVecchio** [comment]
Is the answer as simple as "The Properties field is populated by json.UnMarshal(), and thus this code has no control over it"?

**Comment by casualjim** [comment]
that is correct but in the next version I want to use sorted maps for everything and a serializer that allows us control over this

**Comment by MartinDelVecchio** [comment]
Thanks for your reply.

So it appears that there is nowhere in the go-openapi code that the property names are available in order.

When you say "sorted map", are you referring to a specific package?  I tried to use the ordered_map package, but couldn't get it to work.

I need to figure out a way to get this to work now.  My worst-case scenario is to add an ordinal notation to each property:

    properties:
      code:
        type: integer
        format: int32
        x-uiOrder: 0
      message:
        type: string
        x-uiOrder: 1
      fields:
        type: string
        x-uiOrder: 2

As this is clearly un-maintainable.  Can you offer any other suggestions for the here and now?

Thanks.

**Comment by casualjim** [comment]
this is for the spec or the models generated from the spec?

**Comment by MartinDelVecchio** [comment]
For the spec itself.  We want to include UI information in the JSON schema, including the proper display order for each object's properties.

Thanks.

**Comment by casualjim** [comment]
The spec itself is doable I think to keep everything sorted because it's already using custom serializers for everything, they can be adapted fairly easy. All of the code for it lives here: https://github.com/go-openapi/spec

**Comment by MartinDelVecchio** [comment]
You refer to "custom serializers", but isn't the problem that the YAML deserializer randomizes the property order when it reads the source YAML file?  So any code that serializes that random data will inherit its random order?

Thanks again.

**Comment by casualjim** [comment]
If you update go-openapi/swag and go-openapi/loads then then order of the yaml to json is preserved.
Please close if that is what you needed

**Comment by MartinDelVecchio** [comment]
I will try that now.  We are using Braid, and this is my first experience with updating, so it might be rough going for me.

Thanks!!!

**Comment by MartinDelVecchio** [comment]
OK, I see that in YAMLToJSON(), the YAML data is now in a yaml.MapSlice(), which has maintained the file order.

And I see that this call to convert is to JSON:

	b, err := WriteJSON(jm)

also maintains the order.  At that point, the JSON document is in order.  

But in Analyzed() (loads/spec.go), where it takes this in-order JSON and unmarshals it to a spec.Swagger:

	swspec := new(spec.Swagger)
	if err := json.Unmarshal(raw, swspec); err != nil {
		return nil, err
	}

The order is lost.  This is because spec.Swagger.SwaggerProps.Paths.Paths.PathItem.PathItemProps.Put.OperationProps.Parameters.Parameter.ParamProps.Schema.SchemaProps.Properties is a Go map.

So by the time it arrives in a loads.Document struct, the order is lost.

And I think the use of json.UnMarshal() and various Go maps means that there is no hack I can do to retain the original order there, short of rewriting it without maps.  Which is probably beyond me.

Am I missing something?

Thanks.

**Comment by fredbi** [comment]
Closed with #116
