### ISSUE TITLE
`Ref` is gone after spec expansion

### ISSUE THREAD

**Issue by sdcoffey** [go-openapi/spec#25]
I'm running into an issue where the `Ref` property on a `Schema` object is empty after expanding the root document. This makes it extremely hard to find a `Schema`s parent, or the URI by which that schema was referenced, which is useful for code generation purposes. Am I missing something? perhaps there's a better way to about this. 

Here's an example:

```go
ref := schema.Ref.String()
log.Println(ref) // output: "./some-schema.json"

opts := &opi.ExpandOptions{
	RelativeBase: "/tmp/swagger",
}
if err := opi.ExpandSchemaWithBasePath(schema, parent, nil, opts); err != nil {
	panic(fmt.Errorf("Error expanding shema ref %s -> %s", ref, err))
}

ref := schema.Ref.String()
log.Println(ref) // output: ""
```

This example is somewhat contrived, but in more complex examples, like when this code is called recursively with an already-expanded `schema` as `parent`, it's impossible to know the original path from which the nested schema was referenced. Maybe this is intended behavior. If that's the case, what's the recommended approach to preserve these reference URIs?

**Comment by casualjim** [comment]
This is per spec of jsonref. A $ref can be the only thing that exists on an object, or at least all other properties should be ignored.
You can look things up in the original spec, just keep 2 copies around
the analyzer package allows you to get all the refs and as such you can work out which things were resolved

**Comment by sdcoffey** [comment]
Got it, thanks for the clarification. I started looking at the analysis package shortly after posting here, seems like that will work well. Cheers!
