### ISSUE TITLE
NewRef should return an empty Ref if refURI is empty

### ISSUE THREAD

**Issue by nikhita** [go-openapi/spec#29]
We are using go-openapi for validation of Custom Resources in Kubernetes (https://github.com/kubernetes/kubernetes/pull/47263). 

While using the `spec.NewRef` function, an empty string i.e `spec.NewRef("")` results in a Ref with a `#` - not an empty Ref value. Due to this, we incorporated an [additional check](https://github.com/nikhita/kubernetes/blob/dcb5a820828fe1fc50f1cdcd0ea9267f47cbe7d6/staging/src/k8s.io/apiextensions-apiserver/pkg/apiserver/validation/validation.go#L91).

Looking at the code in https://github.com/go-openapi/jsonreference, it looks like an empty Ref should be produced but I couldn't really figure out why that does not occur.

cc @sttts

**Comment by casualjim** [comment]
It's because of this this line: https://github.com/go-openapi/spec/blob/master/ref.go#L141

**Comment by casualjim** [comment]
would it be ok if it returned:
```json
{"$ref":""}
```

**Comment by nikhita** [comment]
@casualjim That would be perfect, thanks. :+1:

**Comment by casualjim** [comment]
i fixed this now so please close when you've confirmed :)
