### ISSUE TITLE
Transitive refs fail to resolve on local file

### ISSUE THREAD

**Issue by fredbi** [go-openapi/spec#65]
From go-swagger/go-swagger#1429 (see test case there)
Test case on $ref for full response
When response $ref points to another file (./responses.yaml#responses/BadRequest) where a new indirection is declared locally (to #/definitions/Error).

Fails to resolve ./responses.yaml/#definitions/Error

Declaring explicitly './responses.yaml#/definitions/Error' in responses.yaml works around the problem.

**Comment by pytlesk4** [comment]
I can take this, I know what the issue is and how to fix it. I try to get to this by the end of the week.

**Comment by fredbi** [comment]
Thanks. I tried myself to trace and figure out, but this expander stuff I never could quite follow it.

**Comment by fredbi** [comment]
This PR does not solve this issue.

**Comment by pytlesk4** [comment]
Got a pull request incoming, just adding some tests.
