### ISSUE TITLE
spec ExpandSpec with SkipSchemas: true leaves inconsistent remote $ref in schema

### ISSUE THREAD

**Issue by fredbi** [go-openapi/spec#77]
Following the study of go-swagger/go-swagger#1429, I found out that expanding a spec with `SkipSchemas: true` wrongly resolves remote $refs in schemas.

The problem is that when skipping schemas, `$ref`s in parameters and responses are properly resolved,
but if the expanded parameter or response has a schema with a `$ref` (relative to another root), it is simply resolved "as is" without rebasing this ref to the current root. This results in a schema with unresolvable `$ref`, since the root is lost.

I added a testcase derived from go-swagger/go-swagger#1429 to illustrate this.

Main spec:
[swagger.yaml.txt](https://github.com/go-openapi/spec/files/2158779/swagger.yaml.txt)
Remote file:
[responses.yaml.txt](https://github.com/go-openapi/spec/files/2158778/responses.yaml.txt)

This is especially annoying for spec flattening in go-swagger, since it is relying on the SkipSchema feature.

I think that another `SkipRemoteSchemas` option should be made available to tune the expand behavior:
- default: `SkipRemoteSchemas: false`: remote `$ref` in schemas are expanded, even though `SkipSchemas` is true. This ensures that an `ExpandSpec()` with `SkipSchemas: true` does not leave remote $ref's behind.
- `SkipRemoteSchemas: true`: remote `$ref` in schemas are rebased to the current root, but not expanded. This adheres to a _true_ `SkipSchemas; true` (no expansion at all in schemas)

**Comment by casualjim** [comment]
skip schemas only exists for this flattening use case, but lack of rebasing seems like a bug in that implementation

**Comment by fredbi** [comment]
Managed to fix this. More thorough testing is ongoing.
Actually, the proposal above for some optional behavior is unnecessary: it suffices to relocate $ref properly.
