### ISSUE TITLE
Issue with the extension keys

### ISSUE THREAD

**Issue by ninjawule** [go-openapi/spec#89]
Hi ! Thanks for this very good work.

I have a question though: why are the keys for the extensions lower-cased at the moment of adding an extension ?

For example, I need to use the tag groups. I build a tag group list, then add it with the key "x-tagGroups". 

But when I JSON-marshall my Swagger object, I get a "x-taggroups" tag, which is then not recognised by libraries that can handle this OpenAPI extension. 

For now, I have no solution in mind other than forking this repo and using my fork. But I would be pleased to have your answers.

Thanks again

**Comment by casualjim** [comment]
it's interesting because that's not what the code should be doing. https://github.com/go-openapi/spec/blob/master/info.go#L89-L116

Feel free to send a PR with the fix, your expectation is correct but your result says it's a bug

**Comment by fredbi** [comment]
I tried to use extensions tags with various casing, and I can't see any lower-casing in the result.
E.g.:
```yaml
info:
  description: extension recasing test
  x-lowercase:
  - 1
  - 2
  x-CamelCase:
   propCamelized: camel
  X-UPPERCASE: true
```

Marshal it then unmarshal it as json and the case remains unchanged.

However, if I add a conflicting key, like `X-LOWERCASE: true` then, as the key comparison is not case sensitive, the result is undefined (may be `x-lowercase: [ 1, 2]` or `X-LOWERCASE: true`.

The lower-case normalizing of extension keys only occurs if you construct your spec using Add(), etc. methods.

Maybe you could provide us with some details to reproduce this?

**Comment by ninjawule** [comment]
Hi, thank you for these answers.

> The lower-case normalizing of extension keys only occurs if you construct your spec using Add(), etc. methods.

That's precisely what I do. I have an API that's already developed.  But I want to provider its Swagger documentation by building it automatically with reflection tools. So I'm using the Go model here. I instantiate the "Swagger" struct and most of its children info containers. And when I marshall the root object, everything is fine, but for the extensions, which keys are lower cased.

**Comment by fredbi** [comment]
Then this is not really a bug, but a feature of the existing interface offered by the `Extensions` object.

Changing this risks breaks compatibility for other users of this interface (like the `go-swagger` project).

IMHO, you could still propose a change with a settable private flag in struct `Extensions` (e.g. `SetCaseSensitive()` or `WithCaseSensitive()` which would disable the calls to `strings.ToLower()` when explicitly set (not the default). @casualjim how about that?

**Comment by fredbi** [comment]
What I am saying is that pure JSON marshalling/unmarshalling does not tamper with extension case (with the exception of conflicting keys). So this just happens when you are using go methods to build a spec programmatically.

**Comment by casualjim** [comment]
You can still access the extension object directly, then you odn't have that issue, it's not private

**Comment by ninjawule** [comment]
Go point ! I'm going to try like that. Thanks !

**Comment by ninjawule** [comment]
I feel a bit stupid, not having figured that out. It's working now, without using a fork to remove the lower-casing. Thanks ! I guess this issue can be closed now.
